# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- '*'//This pipeline will run whenever you push an update to the GitHub repo

pool:
  vmImage: 'windows-latest'

steps:
- task: gitmirror@0//You can install this task in marketplace
  inputs:
    GitRepoUrl: 'https://giovanifvhenriques@dev.azure.com/{Organization Name}/{Project Name}/_git/{Repo Name}.git'//This is the URL of Azure Repo, you need to add a personal access token in the URL